Update CssStyleSheet.java
HtmlUnit/htmlunit pull request #465
Opened 2022-03-26 16:40 UTC by bharatwaaj

2022-03-26 17:04 UTC, rbri requested changes

2022-03-26 17:04 UTC, rbri commented on src/main/java/com/gargoylesoftware/htmlunit/css/CssStyleSheet.java
> +    public static boolean selectsSpecifiedElement(final BrowserVersion browserVersion, final Selector selector,
you are right, better naming might be a good idea but this method is public and i do not want to break the interface here.

2022-03-26 17:04 UTC, rbri commented on src/main/java/com/gargoylesoftware/htmlunit/css/CssStyleSheet.java
> +                                                  final DomElement element, final String pseudoElement, final boolean fromQuerySelectorAll) {
I guess this reformating breaks the formating rules

2022-03-26 17:04 UTC, rbri commented
see comments, please revert the renaming, and please add your name to the contributor list in the pom,

2022-03-26 17:53 UTC, bharatwaaj commented
> see comments, please revert the renaming, and please add your name to the contributor list in the pom,

Hi, I have reverted the renaming and added my name to contributor list in the pom.xml, thanks a ton!

2022-03-27 09:43 UTC, merged

2022-03-27 09:43 UTC, rbri commented
Many thanks